config/routes.rb
Rails.application.routes.draw do
  resources :github_users
  namespace :api do
    resources :sessions, only: [:create]
  end
  resources :users
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/github_user.rb
class GithubUser < ApplicationRecord
  validates :github_id, uniqueness: true
end

app/controllers/github_users_controller.rb
class GithubUsersController < ApplicationController
  before_action :set_github_user, only: [:show, :edit, :update, :destroy]

  # GET /github_users
  # GET /github_users.json
  def index
    @github_users = GithubUser.all
  end

  # GET /github_users/1
  # GET /github_users/1.json
  def show
  end

  # GET /github_users/new
  def new
    @github_user = GithubUser.new
  end

  # GET /github_users/1/edit
  def edit
  end

  # POST /github_users
  # POST /github_users.json
  def create
    @github_user = GithubUser.new(github_user_params)

    respond_to do |format|
      if @github_user.save
        format.html { redirect_to @github_user, notice: 'Github user was successfully created.' }
        format.json { render :show, status: :created, location: @github_user }
      else
        format.html { render :new }
        format.json { render json: { error: @github_user.errors.full_messages.join(' ,') }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /github_users/1
  # PATCH/PUT /github_users/1.json
  def update
    respond_to do |format|
      if @github_user.update(github_user_params)
        format.html { redirect_to @github_user, notice: 'Github user was successfully updated.' }
        format.json { render :show, status: :ok, location: @github_user }
      else
        format.html { render :edit }
        format.json { render json: { error: @github_user.errors.full_messages.join(' ,') }, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /github_users/1
  # DELETE /github_users/1.json
  def destroy
    @github_user.destroy
    respond_to do |format|
      format.html { redirect_to github_users_url, notice: 'Github user was successfully destroyed.' }
      format.json { render json: { success: :ok } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_github_user
      @github_user = GithubUser.find_by(id: params[:id]) || GithubUser.find_by(github_id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def github_user_params
      params.require(:github_user).permit(:name, :github_id, :avatar_url)
    end
end

app/helpers/github_users_helper.rb
module GithubUsersHelper
end

app/views/github_users/_form.html.erb
<%= form_with(model: github_user, local: true) do |form| %>
  <% if github_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(github_user.errors.count, "error") %> prohibited this github_user from being saved:</h2>

      <ul>
      <% github_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :github_user_name %>
  </div>

  <div class="field">
    <%= form.label :github_id %>
    <%= form.number_field :github_id, id: :github_user_github_id %>
  </div>

  <div class="field">
    <%= form.label :avatar_url %>
    <%= form.text_field :avatar_url, id: :github_user_avatar_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/github_users/edit.html.erb
<h1>Editing Github User</h1>

<%= render 'form', github_user: @github_user %>

<%= link_to 'Show', @github_user %> |
<%= link_to 'Back', github_users_path %>

app/views/github_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Github Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Github</th>
      <th>Avatar url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @github_users.each do |github_user| %>
      <tr>
        <td><%= github_user.name %></td>
        <td><%= github_user.github_id %></td>
        <td><%= github_user.avatar_url %></td>
        <td><%= link_to 'Show', github_user %></td>
        <td><%= link_to 'Edit', edit_github_user_path(github_user) %></td>
        <td><%= link_to 'Destroy', github_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Github User', new_github_user_path %>

app/views/github_users/new.html.erb
<h1>New Github User</h1>

<%= render 'form', github_user: @github_user %>

<%= link_to 'Back', github_users_path %>

app/views/github_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @github_user.name %>
</p>

<p>
  <strong>Github:</strong>
  <%= @github_user.github_id %>
</p>

<p>
  <strong>Avatar url:</strong>
  <%= @github_user.avatar_url %>
</p>

<%= link_to 'Edit', edit_github_user_path(@github_user) %> |
<%= link_to 'Back', github_users_path %>